# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
sass:
    sass_dir: css

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jemoji

  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata